# .github/workflows/app.yaml
name: test dbt compile

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'scripts/**'
      - 'Pipfile'
      - '.gitignore'
      - '.github/**'

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  dbt-test:
    runs-on: [ self-hosted, linux, spellbook-trino ]
    strategy:
      matrix:
        engine: [ 'spark' ]
      max-parallel: 1
    timeout-minutes: 90

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: fix pipenv on the fly
        run: "python3 --version && pipenv clean && pipenv sync"

      - name: dbt dependencies
        run: "pipenv run dbt deps"

      - name: dbt compile
        run: "pipenv run dbt compile --profiles-dir $HOME/.dbt --profile spark"

      - name: dbt run the new model
        run: "pipenv run dbt run --select some_new_dunesql_model --profiles-dir $HOME/.dbt --profile spark"

